### ISSUE TITLE
Referring to name in evaluator defined after run shutsdown Pardinus-cli

### ISSUE THREAD

**Issue by tdelv** [tnelson/Forge#108]
```
#lang forge

aRun : run {}

sig A {}
```

Then, referring to `A` in the evaluator during `aRun` causes PardinusCli to shutdown with

```
No definition found for rS. (line 1, pos 10):
BasicParseError (line 1, pos 10):
[error] [blank] No definition found for rS. (line 1, pos 10):
[error] [blank] BasicParseError (line 1, pos 10):
[error] [blank] No definition found for rS. (line 1, pos 10):
[error] [blank] BasicParseError (line 1, pos 10):
#<eof>
```

**Comment by tnelson** [comment]
Confirming that, lamentably, this issue is still active. Keeping it in this year's stack as I clean up.

**Comment by tnelson** [comment]
This appears resolved as of the multiple-simultaneous-runs change in Pardinus. (The evaluator produces an error saying that there's no entry for A, but Pardinus does not get sent the query.)
