### ISSUE TITLE
VSCode Semantic Highlighting

### ISSUE THREAD

**Issue by bennn** [tnelson/Forge#117]
Add ~syntax~ semantic highlighting to Forge for VSCode users. Make sure that errors highlight the source.

EDIT: after finding the ErrorLens package today (2021-12-18), I'm  not sure a semantic highlighter is needed. Maybe we can get by with a plugin that looks at recent diagnostics.

EDIT 2: well, we need some way of **making** those diagnostics. A language server seems like the most straightforward way. Though, maybe there's a simpler way to get diagnostics from the terminal.

#### How?

- Port the forge grammar from Brag to TextMate (done?)
- Make a language server
- ???

#### Resources

VSCode semantic guide: <https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide>

VSCode languages API, especially `getDiagnostics` <https://code.visualstudio.com/api/references/vscode-api#languages>

VSCode extension samples <https://github.com/microsoft/vscode-extension-samples>

VSCode Error Lens package: <https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens>

VSCode syntax guide: <https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide>

Example: Magic Racket <https://github.com/Eugleo/magic-racket>
Example: DrRacket Colors <https://bitbucket.org/Dima4ka/vs-code-drracket-colorizer/src/master/>

Prototype: [forge-0.0.3.vsix.zip](https://github.com/tnelson/Forge/files/7670693/forge-0.0.3.vsix.zip)
More Prototypes: <https://drive.google.com/drive/u/1/folders/1cuNtlRwgcX2Rr7gGsUoYQPKwXBilDMHb>

**Comment by tnelson** [comment]
@emmiehe  Thanks for doing so much great work on starting this process! I'm closing the issue since the extension is available; we can make new issues as needed.
