### ISSUE TITLE
Poor error message for bad syntax: Number: bad syntax in: (Number "3")

### ISSUE THREAD

**Issue by tnelson** [tnelson/Forge#26]
The following file:
```#lang forge
sig A {}
sig B {}
run {} for 3 but 3 A, 3 B
```

produces this error with no highlight or line number. This happens when pasting in old models from Alloy for update, since Alloy supported adjusting default bounds. 

I'm not proposing that Forge support adjusting default bounds necessarily, just that the error be improved.

**Comment by bennn** [comment]
Today this is not an error:
```
#lang forge

sig A {}
sig B {}
run {} for 3 but 3 A, 3 B

;; > racket main.rkt
;; Forge version: 0.14.2
;; Sterling running. Hit enter to stop service.
;; #vars: (size-variables 0); #primary: (size-primary 0); #clauses: (size-clauses 0)
;; Transl (ms): (time-translation 125); Solving (ms): (time-solving 0)
```
