### ISSUE TITLE
Bug with 'func relation break

### ISSUE THREAD

**Issue by tdelv** [tnelson/Forge#62]
The 'func break when applied to a relation from a sig to itself causes an unsound relation break. It enforces that some node can only point to itself, if anything.

```
#lang forge/core

(sig A)
(relation r (A A) #:is func)

(pred irreflexive
  (no (& r iden)))

(test func-bug ; fails
      #:preds [irreflexive]
      #:scope ([A 3 3])
      #:expect sat)
```

The above code produces the following KKCLI bounds:
```
(r:A [{(16) (17) (18)} :: {(16) (17) (18)}])
(r:r [(-> none none) :: {(16 16) (17 16) (17 17) (17 18) (18 16) (18 17) (18 18)}])
```

**Comment by tdelv** [comment]
There is a temporary fix in no-state which just enforces that 'func uses the predicate form of the break instead of the bounds form; this should be reverted to see the bug, and should be reverted after the bug is fixed.

**Comment by asvarga** [comment]
I tried to handle this case here: https://github.com/tnelson/Forge/blob/119566b56edcc6d189bbbea2d63d502fda8ccd45/forge/breaks.rkt#L602-L614 Either I botched it or the `equal?` check is failing for some reason.

**Comment by tdelv** [comment]
Here, for 
```
sig Node {
    edges: set Node
}
```

If `Node` is 16, 17, 18, 19, then the  upper-bound  on `edges` is  `{(17) (18) (19)} -> {(16) (17) (18) (19)} + {(16 16)}`. This means that 16 can't point to anything besides itself. However, For `Node = N1 + N2 + N3 + N4` and `edges =  N1->N2 + N2->N3 + N3->N4  + N4->N1`, the `edges` relation is functional but nothing points to itself.

**Comment by tnelson** [comment]
I believe this was fixed over the summer; closing issue (with test added on dev).
(The fix is still the formula version of the break, but until we can revise breakers more fully in the presence of forge/functional etc. I think this is OK.)
