### ISSUE TITLE
Check-ex-spec exposes wheat/chaff names

### ISSUE THREAD

**Issue by tdelv** [tnelson/Forge#64]
At the moment, we use raw names for wheats and chaffs when downloading them, making it easy to see how to catch the chaffs for students.

**Comment by bennn** [comment]
Where's the staff script for uploading wheats & chaffs?

Also, `check-ex-spec` should be downloading from the `tnelson/lfs` repo and not `tdelv/lfs-2021-check-ex-spec` right?

(I am thinking the upload script should generate new names for compiled files ... "wheat_0.zo" "0.zo" ....)

**Comment by tdelv** [comment]
The staff script is in tnelson/lfs/check-ex-spec. We need a separate, public repo for the check-ex-spec to download from, so for now I was just using a repo I made.

**Comment by bennn** [comment]
IIRC this was fixed with a staff-only script that renamed files before shipping them.
