### ISSUE TITLE
Add the capability to require just the spec

### ISSUE THREAD

**Issue by tdelv** [tnelson/Forge#80]
We want to be able to require just the spec (sigs, relations, preds, functions) from a given forge program without executing the run statements.

**Comment by bennn** [comment]
If you can put the run statements in a submodule, then you can require the outer bindings by themselves.

The `main` submodule makes this easy, but other names should work.

#### provide.rkt
```
#lang racket/base

(provide sigs)

(define sigs '....)

(module+ main
  (printf "run~n"))
;; racket provide.rkt ==> prints "run"
```

#### require.rkt
```
#lang racket/base

(require "provide.rkt")

sigs
;;; racket require.rkt ==> prints "...." and nothing else
```

Let me know if there are more constraints & I can try another Racket model.

**Comment by tdelv** [comment]
Functionality is implemented (but not tested) in the `require` branch. Writing `(require "file.rkt")` will import a spec (including runs/checks) without executing them. Writing `(execute "file.rkt")` will execute a file, but will not import the spec. Will push to dev after further testing.

**Comment by tnelson** [comment]
I believe that this has been done via the `exec` submodule.
