### ISSUE TITLE
Instance displayed in Sterling does not match instance specified with `inst` in certain circumstances

### ISSUE THREAD

**Issue by P-bibs** [tnelson/Forge#90]
The following code does not produce the correct instance:
```
#lang forge

sig Node {
    g: set Node
}

inst Test {
    Node = (N1 + N2 + N3)
    g = (Node->Node) - iden
}

run {} for Test
```
Instead it produces this instance:
![image](https://user-images.githubusercontent.com/40366824/107575544-006c7c00-6bbe-11eb-9e68-c88321c9abfc.png)
Which is incorrect because it includes self-edges which should have been removed by the line `g = (Node->Node) - iden`

**Comment by tnelson** [comment]
Closing, since this appears to have been resolved with the 2023 restructure of instances (backquoting, etc).
